<a href="https://colab.research.google.com/github/XDzzzzzZyq/AlphaCat/blob/main/demo/demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [ ]:
a = np.random.randint(1, 20, 100)
print(a)

[16  5 10 14 11  8  8 12 17  5  5  2 16 12  8  4  6 16  8  5  5  1 10 13
 10 10 12 17 15 11  2 14  5  3  6 18 19 11 18 12 18  2 10 10  4  4 19 13
  8  7 12 17 17 14 16  1 15 10 13 12 15  5 17 17  3  6  1 16  7  9 17 12
 11  4 19  7  1  7 11 12 19 16  1 10 14 17  4  8  2  5 11  6 19  8  7 15
  6  8 17 17]


In [4]:
x=np.random.random((5,5))
print(x)

[[0.84581122 0.0047413  0.53738309 0.07586965 0.52154375]
 [0.40895055 0.15088068 0.00994345 0.7546082  0.3419517 ]
 [0.60410517 0.01536835 0.67480222 0.7686074  0.80330406]
 [0.03822001 0.2743313  0.15086707 0.96757708 0.02951709]
 [0.32718374 0.0137274  0.81533735 0.53516503 0.78346527]]
